const PptxGenJS = require('pptxgenjs');
const path = require('path');
const fs = require('fs');
const axios = require('axios');

const DOWNLOADS_DIR = path.join(__dirname, '..', 'downloads');

// Ensure downloads directory exists
if (!fs.existsSync(DOWNLOADS_DIR)) fs.mkdirSync(DOWNLOADS_DIR);

// Theme colors
const COLORS = {
  accent: '2563EB',      // Blue
  accentLight: 'DBEAFE', // Light blue
  dark: '1E293B',        // Dark text
  muted: '64748B',       // Muted text
  white: 'FFFFFF',
  bg: 'F8FAFC',
};

/**
 * Downloads an image from a URL and returns it as a base64 data URI.
 * Falls back to null on failure.
 */
const fetchImageAsBase64 = async (url) => {
  try {
    const response = await axios.get(url, {
      responseType: 'arraybuffer',
      timeout: 8000,
    });
    const contentType = response.headers['content-type'] || 'image/jpeg';
    const base64 = Buffer.from(response.data).toString('base64');
    return `data:${contentType};base64,${base64}`;
  } catch {
    return null;
  }
};

/**
 * Builds and saves a .pptx file from slide data.
 * Returns the saved file name.
 */
const buildPptx = async (topic, slides, fileName) => {
  const pptx = new PptxGenJS();

  pptx.layout = 'LAYOUT_WIDE';
  pptx.title = topic;
  pptx.author = 'SlideNova';

  for (let i = 0; i < slides.length; i++) {
    const slide = slides[i];
    const isTitle = i === 0;
    const isConclusion = i === slides.length - 1;

    const pSlide = pptx.addSlide();

    // Background
    pSlide.background = { color: isTitle ? COLORS.accent : COLORS.white };

    // Fetch image
    const imgData = slide.imageUrl
      ? await fetchImageAsBase64(slide.imageUrl)
      : null;

    if (isTitle) {
      // ── Title Slide ──
      if (imgData) {
        pSlide.addImage({
          data: imgData,
          x: 0, y: 0, w: '100%', h: '100%',
          sizing: { type: 'cover', w: '100%', h: '100%' },
        });
        // Dark overlay
        pSlide.addShape(pptx.ShapeType.rect, {
          x: 0, y: 0, w: '100%', h: '100%',
          fill: { color: '000000', transparency: 45 },
          line: { color: '000000', transparency: 100 },
        });
      }

      pSlide.addText(topic, {
        x: 0.5, y: 1.8, w: 12, h: 1.4,
        fontSize: 40, bold: true, color: COLORS.white,
        align: 'center', fontFace: 'Calibri',
      });

      pSlide.addText(slide.title, {
        x: 0.5, y: 3.4, w: 12, h: 0.7,
        fontSize: 20, color: 'DBEAFE',
        align: 'center', fontFace: 'Calibri',
      });

      // Accent bar
      pSlide.addShape(pptx.ShapeType.rect, {
        x: 5.5, y: 4.4, w: 2, h: 0.06,
        fill: { color: COLORS.white },
        line: { color: COLORS.white },
      });

      pSlide.addText('Generated by SlideNova', {
        x: 0.5, y: 5.0, w: 12, h: 0.4,
        fontSize: 11, color: 'BFDBFE',
        align: 'center', fontFace: 'Calibri',
      });
    } else {
      // ── Content / Conclusion Slide ──

      // Top accent bar
      pSlide.addShape(pptx.ShapeType.rect, {
        x: 0, y: 0, w: '100%', h: 0.12,
        fill: { color: COLORS.accent },
        line: { color: COLORS.accent },
      });

      // Slide number badge
      pSlide.addShape(pptx.ShapeType.rect, {
        x: 12.1, y: 0.2, w: 0.6, h: 0.35,
        fill: { color: COLORS.accentLight },
        line: { color: COLORS.accentLight },
        rounding: true,
      });
      pSlide.addText(`${i + 1}`, {
        x: 12.1, y: 0.2, w: 0.6, h: 0.35,
        fontSize: 10, color: COLORS.accent,
        align: 'center', bold: true, fontFace: 'Calibri',
      });

      // Title
      pSlide.addText(slide.title, {
        x: 0.4, y: 0.25, w: 11.5, h: 0.75,
        fontSize: isConclusion ? 28 : 26,
        bold: true, color: COLORS.dark,
        fontFace: 'Calibri',
      });

      // Divider
      pSlide.addShape(pptx.ShapeType.rect, {
        x: 0.4, y: 1.05, w: 1.2, h: 0.05,
        fill: { color: COLORS.accent },
        line: { color: COLORS.accent },
      });

      if (imgData) {
        // Layout: bullets left, image right
        const bulletItems = slide.bullets.map((b) => ({
          text: b,
          options: { bullet: { type: 'bullet', indent: 15 }, paraSpaceAfter: 6 },
        }));

        pSlide.addText(bulletItems, {
          x: 0.4, y: 1.25, w: 7.2, h: 4.2,
          fontSize: 15, color: COLORS.dark,
          fontFace: 'Calibri', valign: 'top',
          lineSpacingMultiple: 1.3,
        });

        pSlide.addImage({
          data: imgData,
          x: 7.9, y: 1.1, w: 4.8, h: 3.6,
          rounding: true,
        });
      } else {
        // Full-width bullets
        const bulletItems = slide.bullets.map((b) => ({
          text: b,
          options: { bullet: { type: 'bullet', indent: 15 }, paraSpaceAfter: 8 },
        }));

        pSlide.addText(bulletItems, {
          x: 0.4, y: 1.25, w: 12.2, h: 4.2,
          fontSize: 16, color: COLORS.dark,
          fontFace: 'Calibri', valign: 'top',
          lineSpacingMultiple: 1.4,
        });
      }

      // Footer
      pSlide.addText(`SlideNova  •  ${topic}`, {
        x: 0.4, y: 5.1, w: 12, h: 0.3,
        fontSize: 9, color: COLORS.muted,
        fontFace: 'Calibri',
      });
    }
  }

  const filePath = path.join(DOWNLOADS_DIR, fileName);
  await pptx.writeFile({ fileName: filePath });
  return filePath;
};

module.exports = { buildPptx };
